jobs:
- job: Windows
  displayName: Windows
  continueOnError: true
  strategy:
    matrix:
      Debug:
        buildConfiguration: "Debug"
      Release:
        buildConfiguration: "Release"
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.300'
    displayName: 'Install .NET Core SDK'
  - script: dotnet msbuild build.proj /p:Configuration=$(buildConfiguration)
    displayName: 'Run Build'

- job: macOS
  displayName: macOS
  continueOnError: true
  strategy:
    matrix:
      Debug:
        buildConfiguration: "Debug"
      Release:
        buildConfiguration: "Release"
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.300'
    displayName: 'Install .NET Core SDK'
  - script: dotnet msbuild build.proj /p:Configuration=$(buildConfiguration)
    displayName: 'Run Build'

- job: Linux
  displayName: Linux
  continueOnError: true
  strategy:
    matrix:
      Debug:
        buildConfiguration: "Debug"
      Release:
        buildConfiguration: "Release"
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.300'
    displayName: 'Install .NET Core SDK'
  - script: dotnet msbuild build.proj /p:Configuration=$(buildConfiguration)
    displayName: 'Run Build'