steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.300'
  displayName: 'Install .NET Core SDK'
- script: dotnet msbuild build.proj /p:Configuration=$(buildConfiguration)
  displayName: 'Run Build'
